Logger impruvements
VladimirDmytriienko/nodeJs24Hw_Volodymyr_Dmytriienko pull request #2
Opened 2024-01-31 12:51 UTC by VladimirDmytriienko

Hello)

2024-01-31 13:44 UTC, evhenious commented on config/default.js
> +    colors_enabled: process.env.COLORS_ENABLED || 0,
Невелике зауваження по стилю - старайся не міксувати camelCase із snake_case. Типовий підхід - змінні в енві snake+капс (COLORS_ENABLED),  назви каталогів та файлів - snake (file_sync, node_modules), let/const в коді, імена методів і подібне - camel (logLevel, isDirectory, writeFile())

2024-01-31 13:45 UTC, evhenious commented on config/default.js
> +module.exports = {
По виставленню дефолтних значень 👍

2024-01-31 13:49 UTC, evhenious commented on utils/logger.js
> +colors.enable();
Краще отут один раз перевірити значення `colorsEnabled` із конфіга, і зробити `colors.enable()` чи `colors.disable()` - при вимкнених кольорах методи пакета `colors` просто повертають незмінну строку, їх можна не прибирати

2024-01-31 13:52 UTC, evhenious commented on utils/logger.js
> +    const isLogLevelEnabled = (level) => {
Доволі заплутана функція, я витратив добряче часу розбираючись в її логіці... Загалом, `простіше` майже завжди значить `краще` - спробуй будь ласка зробити простіше, це можливо)

Ідея з log level weight дуже правильна, але треба трохи дожати :)

2024-01-31 13:55 UTC, evhenious requested changes
Дуже добре, але ти можеш краще) спробуй оптимізувати переключання кольорів і визначення робочого лог левела

2024-02-01 09:41 UTC, VladimirDmytriienko commented
Трохи поліпшив читаємість, зробив простіше)

2024-02-01 10:13 UTC, evhenious commented
> Трохи поліпшив читаємість, зробив простіше)

Показати як просто позбавитись свіча і перезаписування методів на пусті?

2024-02-01 10:39 UTC, VladimirDmytriienko commented
Якщо можна то так, тому що в мене виходить щось тоді не те)

2024-02-01 10:41 UTC, evhenious commented
> Якщо можна то так, тому що в мене виходить щось тоді не те)

все в тебе добре виходить) далі буде крутіше 👍 

Додав три коміти (поправив тобі енв варси трохи, і відполіровав логгер)

2024-02-01 10:44 UTC, evhenious approved these changes

2024-02-01 10:44 UTC, merged

2024-02-01 10:54 UTC, VladimirDmytriienko commented
Цікаво, а взагалі для вирішення чогось часто використовують таку логіку з weight і який варіант швидше працює ?

2024-02-01 11:36 UTC, evhenious commented
> Цікаво, а взагалі для вирішення чогось часто використовують таку логіку з weight і який варіант швидше працює ?

Взагалі, підхід з weight можна застосувати всюди, де є схожа рівнева ієрархія чогось) на декількох американських стрімінгових платформах лог левели працюють дуже схоже на це

А от якщо цікаво про заміну свічей почитати - https://ultimatecourses.com/blog/deprecating-the-switch-statement-for-object-literals

Щодо швидкості об'єкта і свіча - одне й те саме, різниця на рівні погрішності бенчмарків https://www.measurethat.net/Benchmarks/Show/3444/0/switch-vs-object-literal